os:
    - linux
sudo: required
language: generic

services:
  - docker

# mkdir required here to avoid permission problem in script
install:
  - mkdir -p .build/lambda/libraries
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift test
  - ./run-unit-tests.sh

script:
  - ./run-integration-tests.sh